### PR TITLE
modified path in wizard.sh

### PR DESCRIPTION
**Pull request by bluewitch**
Some miss-configurations probably when starting the `wizard.sh`

Haven't been able to duplicate original error

`[Makefile:62: sifnode-standalone-wizard] Error 2`

```
dwulf@Stormbringer:~/sifchain/sifchain-validators/scripts$ latest: Pulling from sifchain/wizard
Digest: sha256:98fb16713cd86821e452ef86112bc214043974322773138d8a05943d4dec92bf
Status: Image is up to date for sifchain/wizard:latest
docker.io/sifchain/wizard:latest
```
stalls here

### CODE REVIEW

**Comment by bluewitch** [comment]
Same output, no errors, but stalls on .logo screen load, empties in # (root?), need to exit and after a delay pushes output
```
dwulf@Stormbringer:~/sifchain/sifchain-validators/scripts$ latest: Pulling from sifchain/wizard
Digest: sha256:98fb16713cd86821e452ef86112bc214043974322773138d8a05943d4dec92bf
Status: Image is up to date for sifchain/wizard:latest
docker.io/sifchain/wizard:latest
```

Using a test Chain ID, to pass into the invoked `wizard.sh`  functions

**Comment by bluewitch** [comment]
Put in SERVICE and IMAGE_TAG variables in the Makefile because of correct flags not being in Makefile.

Invoking by rule
`make sifnode-kubernetes-wizard`

**Comment by bluewitch** [comment]
Pushed up repaired links, edited `Makefile` for `CHAIN_ID`, making progress, invoking from Makefile specifically for `sifnode-standalone-wizard` rule in the `Makefile`

**Comment by bluewitch** [comment]
Ok the env 'blind' error I figured was something buggy in the `env`
```
CHAIN_ID=sifchain-testnet-1 GAS_PRICES=0.5rowan BIND_IP_ADDRESS=127.0.0.1 MONIKER=test MNEMONIC="worry blind fork impulse security shallow virus course stone sleep mercy weekend where snap resource winter oyster trim truly crunch hockey drift east fluid" make SHELL=/bin/bash sifnode-standalone-boot
```

Diffrent Output
```
dwulf@Stormbringer:~/sifchain/sifchain-validators$ CHAIN_ID=sifchain-testnet-1 GAS_PRICES=0.5rowan BIND_IP_ADDRESS=127.0.0.1 MONIKER=test MNEMONIC="worry blind fork impulse security shallow virus course stone sleep mercy weekend where snap resource winter oyster trim truly crunch hockey drift east fluid" make SHELL=/bin/bash sifnode-standalone-boot


                                 .,::,.                .',,'                ',,'
                               .,oxxxxx,             .collll,             'cllll.
                               ,xxx::xx:.           .col;;lll'           ;olc:ll'
                              .oxxl:oxx,           .coo; 'lll'          'ool;;ll'
                              ,xxxooxxc.  ....     ;ool. ;ll;          .cooc:ll,                         ...
                              ,xxxxxl,.   ,dol'   'ooo,.;ll:.          'ooolll;                        'odol.
                            ..cxxxx:.    .odoc.   ;oooccll,           .cooool;                         ,xdo;
                 ..,cc::c,.,oxxxxxx,     .c,.    'oooool:' .....      'ooooc;'..         ....          ,:,.           ...
               .,oxxxxooxxxxxo,:xxxc.   .oxo.    'oooc;' .,oxxddl.    ;oooc;:lll:.   .,:oxxxl,.       :oo;    .;;' .,:lll:.
             .,oxxo,...cxxxxx, ,xxxk;   ,xxx,   .looc. .,oxxxkxdd,   'ooooooc:lll:. .oxxxo:lxdl:.    ,dooo'   'ool::l::lll:.
            .cxxo,. .,oxxxxxx, ,xxdx,  .oxxx,   :doo;';lxxxo:oxdd,   ;oooooc.'llll'.oxxxc. .lddd,    :ooo;   .clllll:.'lll,
            ,xxo. .,oxo,.cxxx, ,xxxx,  ,xxxc.  ,dooooclxxxo..:::,. .;oooooc. ,lll,,oxxxc. .:dddd,   :dooo'   ;ollll; .:lll'
           .oxx;.,oxxo,.,oxxo. ,xxxx, .oxxx,  .ldooo;,oxxx;       :ooooooc. 'llllldxxxc. .:xdddd,  :dooo;   ;oolll;  ,lll:.
           ,xxc,oxxo,,oxxxx:.  ,xxxo. ;xxxo..,lddoo; ,xxxx,     .ldddoooc.  ;lll,:xxxx, .:xxddd:..:ddooo' .cooollc. 'llll'
           ,xxooxxc. .ccc,..  .oxxx,  ;xxx,.:ddddoo' .oxxx,    ,lddddooo'  'llll';xxxxc,oxxxddd,.ldddood;'coooooc.  'llll'
           .oxxxxc.          .:xxxo.  ;xxxoldl:ldoc.  .oxxo:::ldd::dooo;   'llll'.oxxxxxxo,:dddlldl:ldoooooccooo'   'lll:.
            ,xxxo.         .,oxxxo.   .,oxxo::lddd,    .,oxxxdl,..'oodc.   .:lll:..oxxxo,.  :dddl,. .coooc' 'ooc.   'llll'
            ;xxxxo,......,coxxxo,.      ....:ddddd'      .....     ...      .;,,'  .....     ...      ...    ..      ',,,.
           .cxxooxxxxxxxxxxxxo,.          .oddddd;
           ,xxk;..,cccccc,....           .oxolddd,
           .oxk,                        .oxo:ldd:.
            ;xxc.  .,cccccccc.         .oxx::ddl.                                                                   .;,,'.
            .oxxc.,oxxxxxxxxxc.....    ,xxooddd'                         ...';;;;;;;;;;;,...                       .:lllll'
             .,oxxxxxxxxxxxxxxxxxx:....,xxxxxl,                   ...,;;cooooooooooc;;;;coooc;'..                  .:ll::l:.
               .oxxxxxxxxxxxxxxxxxxxxxl:ccc:,.                .,:lddoooooooooooooooc;;;'';'.';;clc;;'..              ';,:l,
                .cxxxxxxxxxxxoc,.:xxxxxx,               ...,:lddooddoc::,........';;;cooooc;'....';;cll:;,,'......',,:ll:'
                 ..,oxxxxxxxxoc:::oxxxo,.           ..,:lddddddddddoooddl:.           ..';cooooc;,'.....';;,;;;:ll:,,...
                    .,oxxxxxxxxxxxxxxxo::,......,::lddddddddddl:;'..;dddoo'                .';;cllllc;;;,'.',,,:ll'
                      ..,::lddddddddddddddddddxxdddddlldddl:,.       ':;;'                      .';;:lllllllllll:'
                            .......';;:loc::ldddddddddddl:.                                          ...........
                                     .:lll:..,:lddlldddlldl,
                                     .:lll:.   .:ddlldd:,lddl.
                                       ...       ... .:ddd::d,
                                                      ,dddlll.
                                                       ,:::,

WARN[0000] The "GAS_PRICE" variable is not set. Defaulting to a blank string. 
[+] Running 1/1
 ⠿ Container sifchain-testnet-1_sifnode_1  Recreated                                                                                  0.1s
Attaching to sifnode_1
sifnode_1  | cannot stat home dir: stat /root/.sifnoded/cosmovisor: no such file or directory
sifnode_1 exited with code 1
```
diffrent error now

**Comment by bluewitch** [comment]
```


                                 .,::,.                .',,'                ',,'
                               .,oxxxxx,             .collll,             'cllll.
                               ,xxx::xx:.           .col;;lll'           ;olc:ll'
                              .oxxl:oxx,           .coo; 'lll'          'ool;;ll'
                              ,xxxooxxc.  ....     ;ool. ;ll;          .cooc:ll,                         ...
                              ,xxxxxl,.   ,dol'   'ooo,.;ll:.          'ooolll;                        'odol.
                            ..cxxxx:.    .odoc.   ;oooccll,           .cooool;                         ,xdo;
                 ..,cc::c,.,oxxxxxx,     .c,.    'oooool:' .....      'ooooc;'..         ....          ,:,.           ...
               .,oxxxxooxxxxxo,:xxxc.   .oxo.    'oooc;' .,oxxddl.    ;oooc;:lll:.   .,:oxxxl,.       :oo;    .;;' .,:lll:.
             .,oxxo,...cxxxxx, ,xxxk;   ,xxx,   .looc. .,oxxxkxdd,   'ooooooc:lll:. .oxxxo:lxdl:.    ,dooo'   'ool::l::lll:.
            .cxxo,. .,oxxxxxx, ,xxdx,  .oxxx,   :doo;';lxxxo:oxdd,   ;oooooc.'llll'.oxxxc. .lddd,    :ooo;   .clllll:.'lll,
            ,xxo. .,oxo,.cxxx, ,xxxx,  ,xxxc.  ,dooooclxxxo..:::,. .;oooooc. ,lll,,oxxxc. .:dddd,   :dooo'   ;ollll; .:lll'
           .oxx;.,oxxo,.,oxxo. ,xxxx, .oxxx,  .ldooo;,oxxx;       :ooooooc. 'llllldxxxc. .:xdddd,  :dooo;   ;oolll;  ,lll:.
           ,xxc,oxxo,,oxxxx:.  ,xxxo. ;xxxo..,lddoo; ,xxxx,     .ldddoooc.  ;lll,:xxxx, .:xxddd:..:ddooo' .cooollc. 'llll'
           ,xxooxxc. .ccc,..  .oxxx,  ;xxx,.:ddddoo' .oxxx,    ,lddddooo'  'llll';xxxxc,oxxxddd,.ldddood;'coooooc.  'llll'
           .oxxxxc.          .:xxxo.  ;xxxoldl:ldoc.  .oxxo:::ldd::dooo;   'llll'.oxxxxxxo,:dddlldl:ldoooooccooo'   'lll:.
            ,xxxo.         .,oxxxo.   .,oxxo::lddd,    .,oxxxdl,..'oodc.   .:lll:..oxxxo,.  :dddl,. .coooc' 'ooc.   'llll'
            ;xxxxo,......,coxxxo,.      ....:ddddd'      .....     ...      .;,,'  .....     ...      ...    ..      ',,,.
           .cxxooxxxxxxxxxxxxo,.          .oddddd;
           ,xxk;..,cccccc,....           .oxolddd,
           .oxk,                        .oxo:ldd:.
            ;xxc.  .,cccccccc.         .oxx::ddl.                                                                   .;,,'.
            .oxxc.,oxxxxxxxxxc.....    ,xxooddd'                         ...';;;;;;;;;;;,...                       .:lllll'
             .,oxxxxxxxxxxxxxxxxxx:....,xxxxxl,                   ...,;;cooooooooooc;;;;coooc;'..                  .:ll::l:.
               .oxxxxxxxxxxxxxxxxxxxxxl:ccc:,.                .,:lddoooooooooooooooc;;;'';'.';;clc;;'..              ';,:l,
                .cxxxxxxxxxxxoc,.:xxxxxx,               ...,:lddooddoc::,........';;;cooooc;'....';;cll:;,,'......',,:ll:'
                 ..,oxxxxxxxxoc:::oxxxo,.           ..,:lddddddddddoooddl:.           ..';cooooc;,'.....';;,;;;:ll:,,...
                    .,oxxxxxxxxxxxxxxxo::,......,::lddddddddddl:;'..;dddoo'                .';;cllllc;;;,'.',,,:ll'
                      ..,::lddddddddddddddddddxxdddddlldddl:,.       ':;;'                      .';;:lllllllllll:'
                            .......';;:loc::ldddddddddddl:.                                          ...........
                                     .:lll:..,:lddlldddlldl,
                                     .:lll:.   .:ddlldd:,lddl.
                                       ...       ... .:ddd::d,
                                                      ,dddlll.
                                                       ,:::,

make[1]: Entering directory '/home/dwulf/sifchain/sifchain-validators'
/bin/bash: -c: line 0: unexpected EOF while looking for matching `"'
/bin/bash: -c: line 1: syntax error: unexpected end of file
make[1]: *** [Makefile:59: sifnode-standalone-boot] Error 1
make[1]: Leaving directory '/home/dwulf/sifchain/sifchain-validators'
dwulf@Stormbringer:~/sifchain/sifchain-validators$ CHAIN_ID=sifchain-testnet-1 GAS_PRICE=0.5rowan BIND_IP_ADDRESS=127.0.0.1 MONIKER=test MNEMONIC="worry blind fork impulse security shallow virus course stone sleep mercy weekend where snap resource winter oyster trim truly crunch hockey drift east fluid" make SHELL=/bin/bash sifnode-standalone-boot


                                 .,::,.                .',,'                ',,'
                               .,oxxxxx,             .collll,             'cllll.
                               ,xxx::xx:.           .col;;lll'           ;olc:ll'
                              .oxxl:oxx,           .coo; 'lll'          'ool;;ll'
                              ,xxxooxxc.  ....     ;ool. ;ll;          .cooc:ll,                         ...
                              ,xxxxxl,.   ,dol'   'ooo,.;ll:.          'ooolll;                        'odol.
                            ..cxxxx:.    .odoc.   ;oooccll,           .cooool;                         ,xdo;
                 ..,cc::c,.,oxxxxxx,     .c,.    'oooool:' .....      'ooooc;'..         ....          ,:,.           ...
               .,oxxxxooxxxxxo,:xxxc.   .oxo.    'oooc;' .,oxxddl.    ;oooc;:lll:.   .,:oxxxl,.       :oo;    .;;' .,:lll:.
             .,oxxo,...cxxxxx, ,xxxk;   ,xxx,   .looc. .,oxxxkxdd,   'ooooooc:lll:. .oxxxo:lxdl:.    ,dooo'   'ool::l::lll:.
            .cxxo,. .,oxxxxxx, ,xxdx,  .oxxx,   :doo;';lxxxo:oxdd,   ;oooooc.'llll'.oxxxc. .lddd,    :ooo;   .clllll:.'lll,
            ,xxo. .,oxo,.cxxx, ,xxxx,  ,xxxc.  ,dooooclxxxo..:::,. .;oooooc. ,lll,,oxxxc. .:dddd,   :dooo'   ;ollll; .:lll'
           .oxx;.,oxxo,.,oxxo. ,xxxx, .oxxx,  .ldooo;,oxxx;       :ooooooc. 'llllldxxxc. .:xdddd,  :dooo;   ;oolll;  ,lll:.
           ,xxc,oxxo,,oxxxx:.  ,xxxo. ;xxxo..,lddoo; ,xxxx,     .ldddoooc.  ;lll,:xxxx, .:xxddd:..:ddooo' .cooollc. 'llll'
           ,xxooxxc. .ccc,..  .oxxx,  ;xxx,.:ddddoo' .oxxx,    ,lddddooo'  'llll';xxxxc,oxxxddd,.ldddood;'coooooc.  'llll'
           .oxxxxc.          .:xxxo.  ;xxxoldl:ldoc.  .oxxo:::ldd::dooo;   'llll'.oxxxxxxo,:dddlldl:ldoooooccooo'   'lll:.
            ,xxxo.         .,oxxxo.   .,oxxo::lddd,    .,oxxxdl,..'oodc.   .:lll:..oxxxo,.  :dddl,. .coooc' 'ooc.   'llll'
            ;xxxxo,......,coxxxo,.      ....:ddddd'      .....     ...      .;,,'  .....     ...      ...    ..      ',,,.
           .cxxooxxxxxxxxxxxxo,.          .oddddd;
           ,xxk;..,cccccc,....           .oxolddd,
           .oxk,                        .oxo:ldd:.
            ;xxc.  .,cccccccc.         .oxx::ddl.                                                                   .;,,'.
            .oxxc.,oxxxxxxxxxc.....    ,xxooddd'                         ...';;;;;;;;;;;,...                       .:lllll'
             .,oxxxxxxxxxxxxxxxxxx:....,xxxxxl,                   ...,;;cooooooooooc;;;;coooc;'..                  .:ll::l:.
               .oxxxxxxxxxxxxxxxxxxxxxl:ccc:,.                .,:lddoooooooooooooooc;;;'';'.';;clc;;'..              ';,:l,
                .cxxxxxxxxxxxoc,.:xxxxxx,               ...,:lddooddoc::,........';;;cooooc;'....';;cll:;,,'......',,:ll:'
                 ..,oxxxxxxxxoc:::oxxxo,.           ..,:lddddddddddoooddl:.           ..';cooooc;,'.....';;,;;;:ll:,,...
                    .,oxxxxxxxxxxxxxxxo::,......,::lddddddddddl:;'..;dddoo'                .';;cllllc;;;,'.',,,:ll'
                      ..,::lddddddddddddddddddxxdddddlldddl:,.       ':;;'                      .';;:lllllllllll:'
                            .......';;:loc::ldddddddddddl:.                                          ...........
                                     .:lll:..,:lddlldddlldl,
                                     .:lll:.   .:ddlldd:,lddl.
                                       ...       ... .:ddd::d,
                                                      ,dddlll.
                                                       ,:::,

[+] Running 1/1
 ⠿ Container sifchain-testnet-1_sifnode_1  Recreated                                                                                  0.1s
Attaching to sifnode_1
sifnode_1  | cannot stat home dir: stat /root/.sifnoded/cosmovisor: no such file or directory
sifnode_1 exited with code 1
dwulf@Stormbringer:~/sifchain/sifchain-validators$ sifchain-testnet-1: Pulling from sifchain/sifnoded
Digest: sha256:26d9e8dc41d5bf445f64eb3da786398afb6cff9f327d9e1e33c0035e0d92801f
Status: Image is up to date for sifchain/sifnoded:sifchain-testnet-1
docker.io/sifchain/sifnoded:sifchain-testnet-1
```
`GAS_PRICES` should be `GAS_PRICE` and portal-ed though  `make SHELL=/bin/bash` I think this fixes the `blind` error.

**Comment by intl-man** [comment]
Closing as has been superseded by a later PR.

**Pull request closed without merging**
